name: Build and Release Rust Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable

    - name: Install dependencies
      run: cargo fetch

    - name: Build project
      run: |
        echo "Building the Hello World project"
        cargo build --release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello-world-binary
        path: target/release/hello-world

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-world-binary
        path: ./target/release/

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./target/release/hello-world
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
