name: Build and Release ActionHero for Windows

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust with MSVC target
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc

    - name: Build project for Windows
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Upload artifact (Windows EXE)
      uses: actions/upload-artifact@v4
      with:
        name: actionhero-windows
        path: target/x86_64-pc-windows-msvc/release/actionhero.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: actionhero-windows
        path: ./dist/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}  # <--- This sets the tag name correctly
        name: Release ${{ github.ref_name }}
        files: ./dist/actionhero.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
