name: Build and Release Rust ActionHero (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for MSVC build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust with MSVC target
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc

    - name: Build project for Windows
      run: |
        echo "Building for Windows (MSVC target)"
        cargo build --release --target x86_64-pc-windows-msvc

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: actionhero-windows-binary
        path: target/x86_64-pc-windows-msvc/release/actionhero.exe

  release:
    needs: build
    runs-on: ubuntu-latest  # You can still use Ubuntu to create the release

    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: actionhero-windows-binary
        path: ./dist/

    - name: Create GitHub Release with Windows binary
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/actionhero.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
